CREATE TABLE IF NOT EXISTS avatars (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_avatar_id INT UNSIGNED NOT NULL,
    source_ref_id INT UNSIGNED NULL,
    avatar_code VARCHAR(64) NOT NULL COMMENT 'DragonBound filename/code (example: mh00000)',
    name VARCHAR(128) NOT NULL,
    slot ENUM('head', 'body', 'eyes', 'flag', 'background', 'foreground', 'exitem') NOT NULL,
    gender ENUM('m', 'f', 'u') NOT NULL DEFAULT 'u',
    min_rank SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    note SMALLINT NOT NULL DEFAULT 0,
    gold_week INT UNSIGNED NOT NULL DEFAULT 0,
    gold_month INT UNSIGNED NOT NULL DEFAULT 0,
    gold_perm INT UNSIGNED NOT NULL DEFAULT 0,
    cash_week INT UNSIGNED NOT NULL DEFAULT 0,
    cash_month INT UNSIGNED NOT NULL DEFAULT 0,
    cash_perm INT UNSIGNED NOT NULL DEFAULT 0,
    stat_pop SMALLINT NOT NULL DEFAULT 0,
    stat_time SMALLINT NOT NULL DEFAULT 0,
    stat_atk SMALLINT NOT NULL DEFAULT 0,
    stat_def SMALLINT NOT NULL DEFAULT 0,
    stat_life SMALLINT NOT NULL DEFAULT 0,
    stat_item SMALLINT NOT NULL DEFAULT 0,
    stat_dig SMALLINT NOT NULL DEFAULT 0,
    stat_shld SMALLINT NOT NULL DEFAULT 0,
    set_key VARCHAR(128) NULL,
    remove_time BIGINT NULL COMMENT 'unix ms; 0/null means no removal date',
    is_unlocked TINYINT(1) NOT NULL DEFAULT 1,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_avatars_code (avatar_code),
    KEY idx_avatars_source_ref (source_ref_id),
    UNIQUE KEY uq_avatars_source (source_avatar_id, avatar_code, slot, gender),
    KEY idx_avatars_slot_gender (slot, gender),
    KEY idx_avatars_enabled_code (enabled, avatar_code),
    KEY idx_avatars_prices (cash_perm, gold_perm, cash_month, gold_month, cash_week, gold_week)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
